### ISSUE TITLE
Karte wird nicht angezeigt

### ISSUE THREAD

**Issue by Sigi-F** [gexclaude/gd_googledirections#3]
Hallo,

der Routenplaner funktioniert wunderbar - allerdings ohne Karte. Mootools ist aktiviert.
Hier der Link: http://www.hfr-tischlerei.de/index.php/anfahrt.html

Hat jemand eine Idee, was ich verkehrt mache? Arbeite mit Contao 3.5.4, habe es aber auch in früheren Contao-Versionen getestet. Gleiches Ergebnis.
Für Hinweise wäre ich sehr dankbar!

Grüße Sigrun

**Comment by gexclaude** [comment]
Hallo Sigrun

Offenbar hast du mittlerweile ein anderes Modul eingesetzt. So ist es schwierig das Problem zu analysieren.

Gruss
Claude

**Comment by Sigi-F** [comment]
Hallo Claude,

das ist sehr nett, dass du dir die Sache anschauen m�chtest. 

Ja, weil ich nicht weitergekommen bin, habe ich erst einmal ein anderes Modul eingesetzt, w�rde aber lieber googledirections nehmen.
Es ist jetzt auf einer Testseite eingestellt: 

http://www.hfr-tischlerei.de/index.php/anfahrt-test.html

W�rde mich �ber eine R�ckmeldung freuen.

Liebe Gr��e aus M�nster
Sigrun

**Comment by gexclaude** [comment]
Wenn du die HTML Elemente ansiehst, dann sieht man, dass die Karte da wäre, einfach nicht sichtbar wegen der Breite des umschliessenden div-Containers (main)
http://pasteboard.co/CE7sI5y.png

In Frontend-Modul kannst du das zu verwendende Layout wählen. Für deine Seite wäre das einspaltige Layout zu verwenden:
http://pasteboard.co/CE9a2sW.png

Dann müsste eigentlich alles klappen.

**Comment by Sigi-F** [comment]
Hallo Claude,

merci, das war es.
Sorry, das Spaltenlayout hatte ich übersehen.
Danke für das schöne Modul.

Gruss, Sigrun
